apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bi-h5-route
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`static.bifrontend.ruqimobility.com`)
      kind: Rule
      services:
        - name: bi-h5
          port: 80