apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portus-route
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portus.bifrontend.domain.com`)
      kind: Rule
      services:
        - name: portus
          port: 80

