apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: registry-route-web
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`registry.bifrontend.domain.com`)
      kind: Rule
      services:
        - name: registry
          port: 5000

